######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 4 15:52:36 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += core gui widgets

# Input
HEADERS += DTW.h main.h mainwindow.h Signal.h
FORMS += mainwindow.ui
SOURCES += DTW.cpp main.cpp mainwindow.cpp Signal.cpp
